"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        s=list(s)
        t=list(t)
        s.sort()
        s.append(" ")
        t.sort()
        for i in range(0,len(t)):
            if t[i]!=s[i]:
                return t[i]
        return t[len(t)-1]


#interesting Counter Solution：
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        from collections import Counter
        s=Counter(s)
        t=Counter(t)
        for item in t:
            if s[item]!=t[item]:
                return item
"""
Counter({'c': 1, 'b': 1, 'a': 1})
Counter({'c': 1, 'e': 1, 'b': 1, 'a': 1})
"""
